name: amazonese-organizadores-frontend CI

on:
  push:
    branches:
    - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout no repositorio
      uses: actions/checkout@v3

    - name: Copiando o arquivo .env
      run: |
        cp .env.example .env

    - name: Substituindo variaveis de ambiente
      uses: franzbischoff/replace_envs@v1
      env:
        NODE_ENV: ${{ vars.NODE_ENV }}
        BACKEND_BASE_URL: ${{ vars.BACKEND_BASE_URL }}
        IBGE_WS_BASE_URL: ${{ vars.IBGE_WS_BASE_URL }}
      with:
        from_file: '.env'
        to_file: '.env'
        commit: 'false'

    - name: Configurando o Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '18.16.0'

    - name: Instalando dependencias e gerando a aplicacao
      run: |
        npm ci
        npm run build

    - name: Autenticacao no Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKER_HUB_USUARIO }}
        password: ${{ vars.DOCKER_HUB_SENHA }}

    - name: Gerando a imagem e subindo para o Docker Hub
      run: |
        docker build -t ${{ vars.DOCKER_HUB_USUARIO }}/amazonese-organizadores-frontend:latest --build-arg HTTP_PORTA=${{ vars.HTTP_PORTA }} .
        docker push ${{ vars.DOCKER_HUB_USUARIO }}/amazonese-organizadores-frontend:latest
