name: amazonese-organizadores-frontend CI

on:
  push:
    branches:
    - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout no repositorio
      uses: actions/checkout@v3

    - name: Copiando o arquivo .env
      run: |
        cp .env.example .env

    - name: Substituindo variaveis de ambiente
      uses: franzbischoff/replace_envs@v1
      env:
        NODE_ENV: ${{ vars.NODE_ENV }}
        BACKEND_BASE_URL: ${{ vars.BACKEND_BASE_URL }}
        IBGE_WS_BASE_URL: ${{ vars.IBGE_WS_BASE_URL }}
      with:
        from_file: '.env'
        to_file: '.env'
        commit: 'false'

    - name: Configurando o Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '18.16.0'

    - name: Instalando dependencias e gerando a aplicacao
      run: |
        npm ci
        npm run build

    - name: Autenticacao no Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ vars.AZURECR_ENDERECO }}
        username: ${{ vars.AZURECR_USUARIO }}
        password: ${{ vars.AZURECR_SENHA }}

    - name: Gerando a imagem e subindo para o Azure Container Registry
      run: |
        docker build -t ${{ vars.AZURECR_ENDERECO }}/amazonese-organizadores-frontend:${{ github.run_id }} --build-arg HTTP_PORTA=${{ vars.HTTP_PORTA }} .
        docker push ${{ vars.AZURECR_ENDERECO }}/amazonese-organizadores-frontend:${{ github.run_id }}

    - name: Implantando a nova versao da aplicacao
      uses: azure/webapps-deploy@v2
      with:
        app-name: '${{ vars.AZURE_WEBAPP_NOME }}'
        publish-profile: ${{ vars.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: '${{ vars.AZURECR_ENDERECO }}/amazonese-organizadores-frontend:${{ github.run_id }}'
