name: amazonese-organizadores-frontend CI

on:
  push:
    branches:
    - main

jobs:
  build_and_deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - name: Checkout no repositorio
      uses: actions/checkout@v3
    - name: Copiando o arquivo .env
      run: |
        cp .env.example .env
    - name: Substituindo variaveis de ambiente
      uses: franzbischoff/replace_envs@v1
      env:
        NODE_ENV: ${{ vars.NODE_ENV }}
        BACKEND_BASE_URL: ${{ vars.BACKEND_BASE_URL }}
        IBGE_WS_BASE_URL: ${{ vars.IBGE_WS_BASE_URL }}
      with:
        from_file: '.env'
        to_file: '.env'
        commit: 'false'
    - name: Configurando o Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '18.16.0'
    - name: Instalando dependencias e gerando a aplicacao
      run: |
        npm ci
        npm run build
    - name: Configurando o Github Pages
      uses: actions/configure-pages@v3
    - name: Subindo os arquivos gerados no build
      uses: actions/upload-pages-artifact@v1
      with:
        path: "./dist"
    - name: Deploy no Github Pages
      id: deployment
      uses: actions/deploy-pages@v2
